version: "2"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
      args:
          # packages versioning:
          IPYTHON: '6.1.*'
          IPYTHON_SQL: '0.3.*'
          PYODBC: '4.0.*'
          LIBGCC: '5.2.*'
          XGBOOST: '0.6a2'
          PYODBC: '4.0.*'
          PANDAS: '0.20.*'
          SCIKIT_LEARN: '0.19.*'
          JUPYTERLAB: '0.27.*'
          NOTEBOOK: '5.2.*'

          PYECHARTS: '0.2.*'
          CUFFLINKS: '0.12.*'
          DECLAR_WIDGET: '0.6.*'
          IPYWIDGETS: '7.0.*'
          SEABORN: '0.8.*'
          JUPY_NBEXT: '0.2.*'

          DASHBOARDS_VER: '0.7.*'
          JUPY_CMS: '0.7.*'
          JUPY_DASH_BUNDLERS: '0.9.*'

    image: juypter_workspace_notebook
    ports:
      - "8888:8888"
    env_file: nb_secrets.env
    environment:
      DASHBOARD_SERVER_URL: http://dashboards:3000/
    volumes:
      - report:/root/report
    restart: always

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kernel
      args:
          # package versions
          JUPY_KERNEL_GATEWAY: '2.0.*'
    image: juypter_workspace_kernel_gateway
    depends_on:
      - notebook
    links:
      - notebook
    environment:
      KG_ALLOW_ORIGIN: '*'
    restart: always

  dashboards:
    build:
      context: .
      dockerfile: Dockerfile.dashboards
      args:
          # npm versioning:
          DASHBOARDS_SERVER_VER: '>=0.8.0 <0.9.0'
    image: juypter_workspace_dashboards_server
    ports:
      - "3000:3000"
    depends_on:
      - kernel_gateway
    links:
      - kernel_gateway
    env_file: db_secrets.env
    volumes:
      - dashboard:/srv/app/data
    environment:
      PORT: 3000
      KERNEL_GATEWAY_URL: http://kernel_gateway:8888
    restart: always
  nbviewer:
    build:
      context:  .
      dockerfile: Dockerfile.nbviewer
    image: jupyter_workspace_nbviewer
    ports:
      - "8080:8080"
    depends_on:
      - notebook
    volumes:
      - report:/report:ro
volumes:
  report:
  dashboard: