version: "2"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          # packages versioning:
          MINICONDA_VERSION: '4.5.12'

          NODEJS: '10.13.*'

          IPYTHON: '7.6.*'
          IPYTHON_SQL: '0.3.*'
          PYODBC: '4.0.*'
          PSYCOPG2: '2.8.*'
          XGBOOST: '0.90'
          PANDAS: '0.24.*'
          SCIKIT_LEARN: '0.19.*'
          JUPYTERLAB: '1.0.*'
          NOTEBOOK: '5.7.8'     #5.7.8 has download issue , so rollback

          R_ESSENTIAL: '3.6.*'

          PYECHARTS: '1.3.*'
          PLOTLY: '4.*'
          IPYWIDGETS: '7.5.*'
          SEABORN: '0.9.*'

          LAB_MANAGER: '1.0'


    image: juypter_workspace_notebook
    ports:
      - "8888:8888"
    env_file: nb_secrets.env
    volumes:
      - report:/root/report
    restart: always

volumes:
  report:
