version: "2"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
      args:
          # packages versioning:
          IPYTHON: '6.2.*'
          IPYTHON_SQL: '0.3.*'
          PYODBC: '4.0.*'
          PSYCOPG2: '2.7.3.*'
          LIBGCC: '7.2.*'
          XGBOOST: '0.7.post3'
          PANDAS: '0.22.*'
          SCIKIT_LEARN: '0.19.*'
          JUPYTERLAB: '0.31.*'
          NOTEBOOK: '5.4.*'

          R_ESSENTIAL: '1.7.*'

          PYECHARTS: '0.3.*'
          CUFFLINKS: '0.12.*'
          IPYWIDGETS: '7.1.*'
          SEABORN: '0.8.*'


    image: juypter_workspace_notebook
    ports:
      - "8888:8888"
    env_file: nb_secrets.env
    volumes:
      - report:/root/report
    restart: always

  nbviewer:
    build:
      context:  .
      dockerfile: Dockerfile.nbviewer
    image: jupyter_workspace_nbviewer
    ports:
      - "8080:8080"
    depends_on:
      - notebook
    volumes:
      - report:/report:ro
volumes:
  report:
