version: "2"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
      args:
          # packages versioning:
          MINICONDA_VERSION: '4.5.4'

          NODEJS: '8.11.*'

          IPYTHON: '6.5.*'
          IPYTHON_SQL: '0.3.*'
          PYODBC: '4.0.*'
          PSYCOPG2: '2.7.5.*'
          LIBGCC: '7.2.*'
          XGBOOST: '0.80'
          PANDAS: '0.23.*'
          SCIKIT_LEARN: '0.19.*'
          JUPYTERLAB: '0.34.*'
          NOTEBOOK: '5.6.*'

          R_ESSENTIAL: '3.5.*'

          PYECHARTS: '0.5.*'
          CUFFLINKS: '0.13.*'
          IPYWIDGETS: '7.4.*'
          SEABORN: '0.9.*'


    image: juypter_workspace_notebook
    ports:
      - "8888:8888"
    env_file: nb_secrets.env
    volumes:
      - report:/root/report
    restart: always

  nbviewer:
    build:
      context:  .
      dockerfile: Dockerfile.nbviewer
    image: jupyter_workspace_nbviewer
    ports:
      - "8080:8080"
    depends_on:
      - notebook
    volumes:
      - report:/report:ro
volumes:
  report:
