version: "2"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    image: juypter_workspace_notebook
    ports:
      - "8888:8888"
    env_file: nb_secrets.env
    environment:
      DASHBOARD_SERVER_URL: http://dashboards:3000/
    volumes:
      - report:/root/report
    restart: always

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kernel
    image: juypter_workspace_kernel_gateway
    depends_on:
      - notebook
    links:
      - notebook
    environment:
      KG_ALLOW_ORIGIN: '*'
    restart: always

  dashboards:
    build:
      context: .
      dockerfile: Dockerfile.dashboards
      args:
          # npm versioning:
          DASHBOARDS_SERVER_VER: '>=0.7.0 <0.8.0'
    image: juypter_workspace_dashboards_server
    ports:
      - "3000:3000"
    depends_on:
      - kernel_gateway
    links:
      - kernel_gateway
    env_file: db_secrets.env
    environment:
      PORT: 3000
      KERNEL_GATEWAY_URL: http://kernel_gateway:8888
    restart: always

volumes:
  report: