version: "2"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          # packages versioning:
          MINICONDA_VERSION: '4.5.12'

          NODEJS: '10.13.*'

          IPYTHON: '7.3.*'
          IPYTHON_SQL: '0.3.*'
          PYODBC: '4.0.*'
          PSYCOPG2: '2.7.6.*'
          LIBGCC: '7.2.*'
          XGBOOST: '0.80'
          PANDAS: '0.24.*'
          SCIKIT_LEARN: '0.19.*'
          JUPYTERLAB: '0.35.*'
          NOTEBOOK: '5.7.5'     #5.7.8 has download issue , so rollback

          R_ESSENTIAL: '3.5.*'

          PYECHARTS: '1.2.*'
          PLOTLY: '3.10.0'
          CUFFLINKS: '0.14.*'
          IPYWIDGETS: '7.4.*'
          SEABORN: '0.9.*'


    image: juypter_workspace_notebook
    ports:
      - "8888:8888"
    env_file: nb_secrets.env
    volumes:
      - report:/root/report
    restart: always

volumes:
  report:
